---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-cert
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - "czd.tplinkdns.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: kubernetes.io/tls
stringData:
  tls.key: ""
  tls.crt: ""
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: chenzhendong@yahoo.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: tls-secret
    solvers:
    - http01:
        ingress:
          class: nginx
          serviceType: ClusterIP

